name = "gabriel-ai-portal"
compatibility_date = "2024-07-01"

[env.production]
name = "gabriel-ai-portal-production"
workers_dev = false
route = "pmerit-ai-platform-portal.pages.dev/*"

[[env.production.kv_namespaces]]
binding = "PORTAL_CONFIG"
id = "portal_config_namespace"

[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://pmerit-ai-platform.pages.dev/api"
PORTAL_VERSION = "1.0.0"
NIGERIAN_CONTEXT = "enabled"
